// Admin Dashboard Action Types

// Fetch Stats
export const FETCH_ADMIN_STATS_REQUEST = 'FETCH_ADMIN_STATS_REQUEST';
export const FETCH_ADMIN_STATS_SUCCESS = 'FETCH_ADMIN_STATS_SUCCESS';
export const FETCH_ADMIN_STATS_FAILURE = 'FETCH_ADMIN_STATS_FAILURE';

// Fetch Booking Statistics
export const FETCH_BOOKING_STATS_REQUEST = 'FETCH_BOOKING_STATS_REQUEST';
export const FETCH_BOOKING_STATS_SUCCESS = 'FETCH_BOOKING_STATS_SUCCESS';
export const FETCH_BOOKING_STATS_FAILURE = 'FETCH_BOOKING_STATS_FAILURE';

// Fetch Customer Analytics
export const FETCH_CUSTOMER_ANALYTICS_REQUEST = 'FETCH_CUSTOMER_ANALYTICS_REQUEST';
export const FETCH_CUSTOMER_ANALYTICS_SUCCESS = 'FETCH_CUSTOMER_ANALYTICS_SUCCESS';
export const FETCH_CUSTOMER_ANALYTICS_FAILURE = 'FETCH_CUSTOMER_ANALYTICS_FAILURE';

// Fetch Revenue Reports
export const FETCH_REVENUE_REPORT_REQUEST = 'FETCH_REVENUE_REPORT_REQUEST';
export const FETCH_REVENUE_REPORT_SUCCESS = 'FETCH_REVENUE_REPORT_SUCCESS';
export const FETCH_REVENUE_REPORT_FAILURE = 'FETCH_REVENUE_REPORT_FAILURE';

// Fetch Users
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// Create User
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

// Update User Role
export const UPDATE_USER_ROLE_REQUEST = 'UPDATE_USER_ROLE_REQUEST';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const UPDATE_USER_ROLE_FAILURE = 'UPDATE_USER_ROLE_FAILURE';

// Toggle User Status (Ban/Unban)
export const TOGGLE_USER_STATUS_REQUEST = 'TOGGLE_USER_STATUS_REQUEST';
export const TOGGLE_USER_STATUS_SUCCESS = 'TOGGLE_USER_STATUS_SUCCESS';
export const TOGGLE_USER_STATUS_FAILURE = 'TOGGLE_USER_STATUS_FAILURE';

// Clear Error
export const CLEAR_ADMIN_STATS_ERROR = 'CLEAR_ADMIN_STATS_ERROR';
