// Bookings Action Types
export const FETCH_BOOKINGS_REQUEST = 'bookings/FETCH_BOOKINGS_REQUEST';
export const FETCH_BOOKINGS_SUCCESS = 'bookings/FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'bookings/FETCH_BOOKINGS_FAILURE';

export const CHECK_IN_BOOKING_REQUEST = 'bookings/CHECK_IN_BOOKING_REQUEST';
export const CHECK_IN_BOOKING_SUCCESS = 'bookings/CHECK_IN_BOOKING_SUCCESS';
export const CHECK_IN_BOOKING_FAILURE = 'bookings/CHECK_IN_BOOKING_FAILURE';

export const VERIFY_BOOKING_REQUEST = 'bookings/VERIFY_BOOKING_REQUEST';
export const VERIFY_BOOKING_SUCCESS = 'bookings/VERIFY_BOOKING_SUCCESS';
export const VERIFY_BOOKING_FAILURE = 'bookings/VERIFY_BOOKING_FAILURE';

export const CLEAR_BOOKINGS_ERROR = 'bookings/CLEAR_BOOKINGS_ERROR';
export const CLEAR_VERIFIED_BOOKING = 'bookings/CLEAR_VERIFIED_BOOKING';
